[build]
builder = "NIXPACKS"

[build.nixpacks]
node_version = "20"
php_version = "8.2"

[build.nixpacks.plan]
providers = ["node", "php"]

[build.nixpacks.phases.setup]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install", "npm run build"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
